### ISSUE TITLE
Labels are swapped

### ISSUE THREAD

**Issue by slhck** [nuomi1/BitrateViewer#1]
Your min/max bitrate labels are swapped.

In your main view controller, you should set:

        infoDataSource[5] = "\(videoAnalyzer.minBitrate) kbps"
        infoDataSource[7] = "\(videoAnalyzer.maxBitrate) kbps"
        infoDataSource[9] = "\(videoAnalyzer.avgBitrate) kbps"

**Comment by nuomi1** [comment]
1.2.0 fix it

**Comment by slhck** [comment]
Thanks, that's great!
