### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by slhck** [nuomi1/BitrateViewer#2]
In order to get dark mode support, you may change the following:

https://github.com/slhck/BitrateViewer/commit/03590ee77047afd6d88923d7a73c657f0c1545cf

until the Charts library is fixed.

This gets you:

![image](https://user-images.githubusercontent.com/582444/55969688-87790200-5c7e-11e9-84db-8971cb14012a.png)

I did not provide a PR for this, as I was making more changes to my fork in order to get it to build under macOS 10.14, and allow more file types etc. However, I may consider deleting my fork again if you'd like to work on some more features with me…?

**Comment by nuomi1** [comment]
Welcome to Pull requests!

**Comment by nuomi1** [comment]
Pull Request are welcome.

**Comment by nuomi1** [comment]
finish in #3
